import type {
  ThemeTokenModes,
  ThemeTokenOverrides,
} from "@deepseek-ai/dsh-client-ui-theme/client";

/** One palette-mode pair required by the host theme runtime. */
function modes(light: string, dark: string): ThemeTokenModes {
  return { light, dark };
}

/**
 * Animal Island palette overrides for the surrounding DSH Desktop surfaces.
 * The local `--muzi-host-*` values precede DSH aliases so every alias can
 * reference a stable, acyclic palette value in both color schemes.
 */
export const MUZI_HOST_THEME_TOKENS: ThemeTokenOverrides = Object.freeze({
  "--muzi-host-canvas": modes("#FFF7E8", "#2C211B"),
  "--muzi-host-cream": modes("#FFFDF7", "#382A22"),
  "--muzi-host-paper": modes("#FFF8EA", "#443229"),
  "--muzi-host-sand": modes("#F2E2BD", "#594133"),
  "--muzi-host-sand-strong": modes("#E6C88E", "#72533D"),
  "--muzi-host-bark": modes("#694633", "#F1D8AF"),
  "--muzi-host-bark-soft": modes("#8A6147", "#D1AA7C"),
  "--muzi-host-bark-deep": modes("#3F2B22", "#241A16"),
  "--muzi-host-leaf": modes("#5B9870", "#8DC49A"),
  "--muzi-host-leaf-hover": modes("#477E5A", "#A9D8A7"),
  "--muzi-host-mint": modes("#D8EFD8", "#304C39"),
  "--muzi-host-mint-strong": modes("#B7DDBA", "#42674C"),
  "--muzi-host-sun": modes("#D9A83D", "#F0C867"),
  "--muzi-host-petal": modes("#F2C8A6", "#875C45"),
  "--muzi-host-rose": modes("#BD6655", "#E69980"),
  "--muzi-host-focus": modes("#6EA972", "#F0C867"),
  "--muzi-host-code": modes("#F7ECD3", "#30241D"),
  "--muzi-host-shadow": modes("rgba(89, 61, 40, 0.12)", "rgba(20, 13, 10, 0.3)"),

  "--dsw-alias-bg-base": modes("var(--muzi-host-canvas)", "var(--muzi-host-canvas)"),
  "--dsw-alias-bg-layer-1": modes("var(--muzi-host-cream)", "var(--muzi-host-cream)"),
  "--dsw-alias-bg-layer-2": modes("var(--muzi-host-paper)", "var(--muzi-host-paper)"),
  "--dsw-alias-bg-layer-3": modes("#FFF1D5", "#4D392E"),
  "--dsw-alias-bg-mask-1": modes("rgba(70, 48, 34, 0.24)", "rgba(20, 13, 10, 0.48)"),
  "--dsw-alias-bg-mask-2": modes("rgba(70, 48, 34, 0.12)", "rgba(20, 13, 10, 0.28)"),
  "--dsw-alias-bg-mask-3": modes("rgba(63, 43, 34, 0.48)", "rgba(20, 13, 10, 0.58)"),
  "--dsw-alias-bg-mask-photo": modes("rgba(63, 43, 34, 0.86)", "rgba(20, 13, 10, 0.88)"),
  "--dsw-alias-bg-mask-drop": modes("rgba(255, 253, 247, 0.76)", "rgba(44, 33, 27, 0.78)"),
  "--dsw-alias-bg-module-platform": modes("var(--muzi-host-sand)", "#4D392E"),
  "--dsw-alias-bg-multi-select": modes("var(--muzi-host-mint)", "var(--muzi-host-mint)"),
  "--dsw-alias-bg-overlay": modes("#FFF8EA", "#533D30"),
  "--dsw-alias-bg-skeleton": modes("rgba(137, 97, 70, 0.1)", "rgba(241, 216, 175, 0.1)"),

  "--dsw-alias-border-inverted2": modes("rgba(255, 253, 247, 0.32)", "rgba(241, 216, 175, 0.16)"),
  "--dsw-alias-border-inverted": modes("rgba(255, 253, 247, 0.56)", "rgba(241, 216, 175, 0.24)"),
  "--dsw-alias-border-l1": modes("rgba(105, 70, 51, 0.12)", "rgba(241, 216, 175, 0.12)"),
  "--dsw-alias-border-l2-darkmode-thin": modes("rgba(105, 70, 51, 0.18)", "rgba(241, 216, 175, 0.16)"),
  "--dsw-alias-border-l2": modes("rgba(105, 70, 51, 0.2)", "rgba(241, 216, 175, 0.2)"),
  "--dsw-alias-border-l3": modes("rgba(105, 70, 51, 0.28)", "rgba(241, 216, 175, 0.28)"),
  "--dsw-alias-border-l4": modes("rgba(105, 70, 51, 0.38)", "rgba(241, 216, 175, 0.38)"),

  "--dsw-alias-brand-primary-invert": modes("var(--muzi-host-cream)", "var(--muzi-host-bark-deep)"),
  "--dsw-alias-brand-primary-new-colorprimary-new-color": modes("var(--muzi-host-leaf)", "var(--muzi-host-leaf-hover)"),
  "--dsw-alias-brand-primary": modes("var(--muzi-host-leaf)", "var(--muzi-host-leaf)"),
  "--dsw-alias-brand-text": modes("var(--muzi-host-bark)", "var(--muzi-host-bark)"),
  "--dsw-alias-focus": modes("var(--muzi-host-focus)", "var(--muzi-host-focus)"),
  "--dsw-alias-focus-ring": modes("0 0 0 3px color-mix(in srgb, var(--muzi-host-focus) 36%, transparent)", "0 0 0 3px color-mix(in srgb, var(--muzi-host-focus) 40%, transparent)"),

  "--dsw-alias-button-contrast-fill": modes("var(--muzi-host-bark)", "var(--muzi-host-cream)"),
  "--dsw-alias-button-elevated-fill": modes("var(--muzi-host-cream)", "#4D392E"),
  "--dsw-alias-button-floating-fill": modes("var(--muzi-host-cream)", "#533D30"),
  "--dsw-alias-button-floating-hover": modes("var(--muzi-host-sand)", "#624734"),
  "--dsw-alias-button-ghost-active-border": modes("var(--muzi-host-leaf)", "var(--muzi-host-leaf-hover)"),
  "--dsw-alias-button-ghost-active-fill": modes("var(--muzi-host-mint)", "var(--muzi-host-mint)"),
  "--dsw-alias-button-ghost-active-hover": modes("var(--muzi-host-mint-strong)", "#4B7453"),
  "--dsw-alias-button-info-fill": modes("var(--muzi-host-sun)", "var(--muzi-host-sun)"),
  "--dsw-alias-button-info-hover": modes("#BF8C2D", "#F6D47A"),
  "--dsw-alias-button-primary-dimmed": modes("var(--muzi-host-mint)", "#496C4C"),
  "--dsw-alias-button-primary-fill": modes("var(--muzi-host-leaf)", "var(--muzi-host-leaf)"),
  "--dsw-alias-button-primary-hover": modes("var(--muzi-host-leaf-hover)", "var(--muzi-host-leaf-hover)"),
  "--dsw-alias-button-tool-bar-fill-invisible": modes("rgba(105, 70, 51, 0.16)", "rgba(241, 216, 175, 0.18)"),
  "--dsw-alias-button-tool-bar-fill": modes("rgba(105, 70, 51, 0.38)", "rgba(241, 216, 175, 0.36)"),
  "--dsw-alias-button-tool-bar-hover": modes("rgba(105, 70, 51, 0.5)", "rgba(241, 216, 175, 0.48)"),

  "--dsw-alias-interactive-bg-active": modes("rgba(91, 152, 112, 0.2)", "rgba(141, 196, 154, 0.24)"),
  "--dsw-alias-interactive-bg-hover-accent": modes("rgba(91, 152, 112, 0.16)", "rgba(141, 196, 154, 0.22)"),
  "--dsw-alias-interactive-bg-hover-danger": modes("rgba(189, 102, 85, 0.12)", "rgba(230, 153, 128, 0.18)"),
  "--dsw-alias-interactive-bg-hover-solid": modes("var(--muzi-host-sand)", "#4D392E"),
  "--dsw-alias-interactive-bg-hover": modes("rgba(105, 70, 51, 0.08)", "rgba(241, 216, 175, 0.1)"),

  "--dsw-alias-label-caption": modes("var(--muzi-host-bark-soft)", "#C49D73"),
  "--dsw-alias-label-dimmed": modes("#B18765", "#9B785D"),
  "--dsw-alias-label-primary-bluish": modes("var(--muzi-host-bark)", "var(--muzi-host-bark)"),
  "--dsw-alias-label-primary-dimmed": modes("#4D3529", "#E8CFA7"),
  "--dsw-alias-label-primary-foreground": modes("var(--muzi-host-cream)", "var(--muzi-host-bark-deep)"),
  "--dsw-alias-label-primary-inverted": modes("var(--muzi-host-cream)", "var(--muzi-host-bark-deep)"),
  "--dsw-alias-label-primary": modes("var(--muzi-host-bark-deep)", "#F1D8AF"),
  "--dsw-alias-label-secondary": modes("var(--muzi-host-bark)", "#D1AA7C"),
  "--dsw-alias-label-tertiary": modes("var(--muzi-host-bark-soft)", "#B98F68"),

  "--dsw-alias-markdown-citation": modes("var(--muzi-host-mint)", "#3B5940"),
  "--dsw-alias-markdown-code-block-banner": modes("#F1E0BB", "#3B2C23"),
  "--dsw-alias-markdown-code-block": modes("var(--muzi-host-code)", "var(--muzi-host-code)"),
  "--dsw-alias-markdown-code-segment-selected": modes("var(--muzi-host-cream)", "#49362B"),
  "--dsw-alias-markdown-code-segment-unselected": modes("#F0DFBA", "#3B2C23"),
  "--dsw-alias-markdown-inline-code": modes("#F4E4C1", "#49362B"),
  "--dsw-alias-markdown-placeholder": modes("#EAD5AC", "#453228"),
  "--dsw-alias-markdown-tag": modes("#E8D2AA", "#4A352A"),

  "--dsw-alias-scrollbar-bg-l1": modes("#DEC79A", "#72533D"),
  "--dsw-alias-scrollbar-bg-l2": modes("#D1B581", "#896146"),
  "--dsw-alias-scrollbar-hover-l1": modes("#BD9566", "#AE805C"),
  "--dsw-alias-scrollbar-hover-l2": modes("#A87C55", "#C89A70"),

  "--dsw-alias-state-business-primary": modes("var(--muzi-host-leaf)", "var(--muzi-host-leaf-hover)"),
  "--dsw-alias-state-business-tertiary": modes("var(--muzi-host-mint)", "#304C39"),
  "--dsw-alias-state-error-primary": modes("var(--muzi-host-rose)", "var(--muzi-host-rose)"),
  "--dsw-alias-state-error-secondary": modes("#D88472", "#F0B09A"),
  "--dsw-alias-state-success-primary": modes("var(--muzi-host-leaf)", "var(--muzi-host-leaf-hover)"),
  "--dsw-alias-state-success-secondary": modes("#86BA8F", "#A9D8A7"),
  "--dsw-alias-state-success-tertiary": modes("var(--muzi-host-mint)", "#304C39"),
  "--dsw-alias-state-warn-label": modes("#9C6D21", "#F0C867"),
  "--dsw-alias-state-warn-primary": modes("var(--muzi-host-sun)", "var(--muzi-host-sun)"),
  "--dsw-alias-state-warn-secondary": modes("#EDC56C", "#F7DA8A"),
  "--dsw-alias-state-warn-tertiary": modes("#FFF0C9", "#5A4222"),
  "--dsw-alias-toast-bg": modes("var(--muzi-host-bark-deep)", "#201713"),
  "--dsw-alias-tooltip-bg": modes("#50362A", "#201713"),

  "--dsw-specific-bubble-highlight": modes("var(--muzi-host-mint-strong)", "#42674C"),
  "--dsw-specific-bubble": modes("#EAF5E6", "#344D3A"),
  "--dsw-specific-input-major": modes("var(--muzi-host-cream)", "#49362B"),
  "--dsw-specific-login-input": modes("#FFF4DE", "#3B2C23"),
  "--dsw-specific-menu": modes("var(--muzi-host-cream)", "#4D392E"),
  "--dsw-specific-selector": modes("var(--muzi-host-sand)", "#4D392E"),
  "--dsw-specific-sidebar-fill": modes("#FFF1D5", "#33261F"),
  "--dsw-specific-sidebar-nav-item-active-accent": modes("var(--muzi-host-mint)", "#3B5940"),
  "--dsw-specific-sidebar-nav-item-active": modes("#F1DFBA", "#4D392E"),
  "--dsw-specific-sidebar-nav-item-hover": modes("#F8EACD", "#433129"),
  "--dsw-specific-tip": modes("#F2E2BD", "#49362B"),

  "--dsw-font-family": modes("Nunito, 'Noto Sans SC', 'Microsoft YaHei', sans-serif", "Nunito, 'Noto Sans SC', 'Microsoft YaHei', sans-serif"),
  "--dsw-shadow-lv1": modes("0 2px 6px rgba(89, 61, 40, 0.1)", "0 2px 6px rgba(20, 13, 10, 0.22)"),
  "--dsw-shadow-lv1-blur": modes("0 5px 14px rgba(89, 61, 40, 0.08)", "0 5px 14px rgba(20, 13, 10, 0.18)"),
  "--dsw-shadow-lv2": modes("0 6px 18px rgba(89, 61, 40, 0.1)", "0 6px 18px rgba(20, 13, 10, 0.24)"),
  "--dsw-shadow-lv3": modes("0 12px 28px rgba(89, 61, 40, 0.14)", "0 12px 28px rgba(20, 13, 10, 0.32)"),
});
