import { execFileSync, spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";
const checker = resolve("scripts/check-mz-names.mjs");
describe("MZ naming guard", () => {
  it("accepts the current repository", () => {
    expect(execFileSync(process.execPath, [checker], { encoding: "utf8" })).toContain("MZ naming check passed");
  });
  it("allows generator attribution only in the icon provenance files", () => {
    const root = mkdtempSync(join(tmpdir(), "mz-icon-provenance-"));
    mkdirSync(join(root, "docs"), { recursive: true });
    mkdirSync(join(root, "src/client/appearance/assets/icons"), { recursive: true });
    writeFileSync(join(root, "docs/iconography.md"), "Generated by oil-icon.\n");
    writeFileSync(join(root, "src/client/appearance/assets/icons/manifest.json"), JSON.stringify({ source: "oil-icon" }));
    expect(spawnSync(process.execPath, [checker, root]).status).toBe(0);
    mkdirSync(join(root, "src"), { recursive: true });
    writeFileSync(join(root, "src/plugin.ts"), 'const name="oil-icon";');
    const result = spawnSync(process.execPath, [checker, root], { encoding: "utf8" });
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("src/plugin.ts:1");
  });
  it("rejects old names outside the documented exceptions", () => {
    const root = mkdtempSync(join(tmpdir(), "mz-naming-"));
    mkdirSync(join(root, "src"));
    writeFileSync(join(root, "src", "plugin.ts"), 'const name="oil_wait_export";');
    const result = spawnSync(process.execPath, [checker, root], { encoding: "utf8" });
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("src/plugin.ts:1");
    writeFileSync(join(root, "src", "plugin.ts"), 'const name="oil-subtitle";');
    expect(spawnSync(process.execPath, [checker, root]).status).toBe(0);
  });
});
