/** Bundled, verified artwork. Generated by build-appearance.mjs. */
import icon0 from "./assets/icons/archive.png";
import icon1 from "./assets/icons/calendar.png";
import icon2 from "./assets/icons/content.png";
import icon3 from "./assets/icons/covers.png";
import icon4 from "./assets/icons/hotspots.png";
import icon5 from "./assets/icons/inspiration.png";
import icon6 from "./assets/icons/knowledge-graph.png";
import icon7 from "./assets/icons/knowledge.png";
import icon8 from "./assets/icons/projects.png";
import icon9 from "./assets/icons/publishing.png";
import icon10 from "./assets/icons/search.png";
import icon11 from "./assets/icons/sessions.png";
import icon12 from "./assets/icons/settings.png";
import icon13 from "./assets/icons/sources.png";
import icon14 from "./assets/icons/tasks.png";
import icon15 from "./assets/icons/video.png";
import icon16 from "./assets/icons/refresh.png";
import icon17 from "./assets/icons/view-options.png";
import icon18 from "./assets/icons/copy.png";
import icon19 from "./assets/icons/clear.png";
import icon20 from "./assets/icons/back.png";
import icon21 from "./assets/icons/sidebar-open.png";
import icon22 from "./assets/icons/sidebar-close.png";
import icon23 from "./assets/icons/fit-view.png";
import icon24 from "./assets/icons/folder-open.png";
import icon25 from "./assets/icons/external-link.png";
import icon26 from "./assets/icons/add.png";
import icon27 from "./assets/icons/remove.png";
import icon28 from "./assets/icons/stop.png";
import icon29 from "./assets/icons/connect.png";
import icon30 from "./assets/icons/disconnect.png";
import icon31 from "./assets/icons/verify.png";
import icon32 from "./assets/icons/ssh.png";
import icon33 from "./assets/icons/skills.png";
export const BUNDLED_ICONS = {
  "archive": icon0,
  "calendar": icon1,
  "content": icon2,
  "covers": icon3,
  "hotspots": icon4,
  "inspiration": icon5,
  "knowledge-graph": icon6,
  "knowledge": icon7,
  "projects": icon8,
  "publishing": icon9,
  "search": icon10,
  "sessions": icon11,
  "settings": icon12,
  "sources": icon13,
  "tasks": icon14,
  "video": icon15,
  "refresh": icon16,
  "view-options": icon17,
  "copy": icon18,
  "clear": icon19,
  "back": icon20,
  "sidebar-open": icon21,
  "sidebar-close": icon22,
  "fit-view": icon23,
  "folder-open": icon24,
  "external-link": icon25,
  "add": icon26,
  "remove": icon27,
  "stop": icon28,
  "connect": icon29,
  "disconnect": icon30,
  "verify": icon31,
  "ssh": icon32,
  "skills": icon33,
} as const;
