/** Text keys owned by the inspiration ledger surfaces. */
const inspirationZhRaw = {
  title: "灵感",
  search: "搜索",
  refresh: "刷新",
  new: "新搜索",
  running: "运行中",
  history: "历史记录",
  draft: "未运行",
  topic: "主题",
  optionalTopic: "主题（可选）",
  researchMode: "研究方式",
  searchTopic: "主题搜索",
  hotspots: "获取热点",
  getHotspots: "获取",
  topicPlaceholder: "例如：AI 写作工作流",
  hotspotPlaceholder: "例如：内容创作",
  range: "时间范围",
  dateZone: "日期按北京时间计算，包含起止两天。",
  noMaterials: "暂无可靠参考素材，请调整主题或时间范围后重试。",
  noSources: "暂无可靠来源。",
  reportMissing: "未获得可用结果。请检查模型配置后重试，或在“更多”中查看会话。",
  historySearch: "搜索历史",
  range24h: "过去 24 小时",
  range7d: "过去 7 天",
  range30d: "过去 30 天",
  rangecustom: "自定义日期",
  startDate: "开始日期",
  endDate: "结束日期",
  dateRequired: "请填写开始和结束日期",
  dateOrder: "开始日期不能晚于结束日期",
  topicRequired: "请输入创作主题",
  copy: "复制结果",
  copied: "已复制结果与来源",
  more: "更多",
  earlierReports: "此记录的其他报告",
  summary: "总结",
  materials: "参考素材",
  timeWindow: "时间范围（北京时间，结束时刻不含）",
  empty: "还没有搜索记录",
  loading: "正在读取搜索记录",
  retry: "重试",
  active: "当前研究",
  openSession: "打开 Agent 会话",
  rerun: "重新搜索",
  stop: "停止本次",
  promote: "转为内容",
  obsidian: "在 Obsidian 中打开",
  sources: "来源",
  status: "状态",
  details: "研究报告",
  findings: "关键发现",
  disagreements: "分歧与未知",
  angles: "创作角度",
  published: "发布",
  unknown: "未知",
  integrityMissing: "报告文件已被移除。",
  integrityChanged: "报告文件已在外部修改，已停止使用该引用。",
  integrityUnavailable: "报告目前不可读取。",
  task: "每日研究任务",
  authorization:
    "启用即授权模型服务按此时间访问公开网络开展研究，并把研究报告写入 Creator Studio；授权持续到你暂停或归档该任务。",
  archived: "已归档",
  editPauses:
    "修改主题、来源、调研模式或时间后，任务会自动暂停，需要重新启用授权。",
  queued: "已排队",
  ready: "报告已就绪",
  partial: "部分完成",
  failed: "失败",
  attention: "需要处理",
  cancelled: "已取消",
  interrupted: "已中断",
  emptyReport: "选择一条灵感或报告以查看详情。",
  started: "已开始调研",
  stopped: "已停止本次调研",
  error: "操作未完成，请重试。",
  badgeAttention: "待处理",
  badgeRunning: "运行中",
  badgeUnread: "新结果",
} as const;

type InspirationLocalKey = keyof typeof inspirationZhRaw;
/** Namespaced translation keys owned by the inspiration ledger. */
export type InspirationCopyKey = `inspiration.${InspirationLocalKey}`;

export const inspirationZh: Record<InspirationCopyKey, string> =
  Object.fromEntries(
    Object.entries(inspirationZhRaw).map(([key, value]) => [
      `inspiration.${key}`,
      value,
    ]),
  ) as Record<InspirationCopyKey, string>;

const inspirationEnRaw: Record<InspirationLocalKey, string> = {
  title: "Inspiration",
  search: "Search",
  refresh: "Refresh",
  new: "New search",
  running: "Running",
  history: "History",
  draft: "Not run",
  topic: "Topic",
  optionalTopic: "Topic (optional)",
  researchMode: "Research type",
  searchTopic: "Search topic",
  hotspots: "Get hotspots",
  getHotspots: "Get",
  topicPlaceholder: "For example, AI writing workflows",
  hotspotPlaceholder: "For example, content creation",
  range: "Time range",
  dateZone: "Dates include both selected days in Asia/Shanghai.",
  noMaterials:
    "No reliable material found. Adjust the topic or date range and try again.",
  noSources: "No reliable sources found.",
  reportMissing:
    "No usable results were returned. Check the model configuration and retry, or open the session under More.",
  historySearch: "Search history",
  range24h: "Past 24 hours",
  range7d: "Past 7 days",
  range30d: "Past 30 days",
  rangecustom: "Custom dates",
  startDate: "Start date",
  endDate: "End date",
  dateRequired: "Enter a start and end date",
  dateOrder: "The start date cannot be after the end date",
  topicRequired: "Enter a creative topic",
  copy: "Copy results",
  copied: "Results and source links copied",
  more: "More",
  earlierReports: "Other reports for this record",
  summary: "Summary",
  materials: "Reference material",
  timeWindow: "Time range (Asia/Shanghai, exclusive end)",
  empty: "No search history yet.",
  loading: "Loading search history",
  retry: "Retry",
  active: "Active research",
  openSession: "Open Agent session",
  rerun: "Search again",
  stop: "Stop this run",
  promote: "Turn into content",
  obsidian: "Open in Obsidian",
  sources: "Sources",
  status: "Status",
  details: "Research report",
  findings: "Key findings",
  disagreements: "Disagreements and unknowns",
  angles: "Creative angles",
  published: "Published",
  unknown: "Unknown",
  integrityMissing: "The report file was removed.",
  integrityChanged:
    "The report file changed outside Muzi Creator, so this reference is blocked.",
  integrityUnavailable: "The report cannot be read right now.",
  task: "Daily research task",
  authorization:
    "Enabling authorizes the model service to research the public web at this time and write the report into Creator Studio. This authorization remains active until you pause or archive the task.",
  archived: "Archived",
  editPauses:
    "Changing the topic, sources, research mode, or time pauses the task until you authorize it again.",
  queued: "Queued",
  ready: "Report ready",
  partial: "Partial",
  failed: "Failed",
  attention: "Needs attention",
  cancelled: "Cancelled",
  interrupted: "Interrupted",
  emptyReport: "Select an inspiration or report to view its details.",
  started: "Research started",
  stopped: "This research run was stopped.",
  error: "The action did not finish. Please try again.",
  badgeAttention: "Needs attention",
  badgeRunning: "Running",
  badgeUnread: "New results",
};

export const inspirationEn: Record<InspirationCopyKey, string> =
  Object.fromEntries(
    Object.entries(inspirationEnRaw).map(([key, value]) => [
      `inspiration.${key}`,
      value,
    ]),
  ) as Record<InspirationCopyKey, string>;
