#!/usr/bin/env node
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { labPaths, prepareLabPath } from "./lab-paths.mjs";
import { setupLab } from "./lab-setup.mjs";

function yamlString(value) {
  return JSON.stringify(value);
}

export async function writeLabConfig(repositoryRoot) {
  const paths = await setupLab(repositoryRoot);
  const config = {
    externalActionsEnabled: false,
    libraryRoot: paths.library,
    creatorRoot: paths.library,
    atlasRoot: paths.atlas,
    trellisProjectsRoot: paths.trellis,
    dataDir: paths.data,
    subtitleSkillDir: join(paths.skills, "subtitle"),
    coverSkillDir: join(paths.skills, "cover"),
    videoPublisherSkillDir: join(paths.skills, "video-publisher"),
    obsidianExecutable: "",
    enabledPublishTargets: [],
    credentials: {},
    lab: { isolated: true, repositoryRoot: paths.root },
  };
  for (const directory of [config.subtitleSkillDir, config.coverSkillDir, config.videoPublisherSkillDir]) {
    await prepareLabPath(paths.root, directory);
    await mkdir(directory, { recursive: true });
  }
  const manifest = {
    name: "dsh-profile-web-muzi-creator-lab",
    private: true,
    dependencies: { "dsh-muzi-creator": `link:${paths.root.replaceAll("\\", "/")}` },
    dsh: {
      profile: {
        bundles: ["@deepseek-ai/dsh-base", "@deepseek-ai/dsh-web-app", "dsh-muzi-creator"],
      },
    },
  };
  const patch = [
    "# Generated by pnpm lab:config. All writable Muzi Creator paths remain under .lab.",
    "- id: dsh-muzi-creator",
    "  config:",
    `    libraryRoot: ${yamlString(config.libraryRoot)}`,
    `    creatorRoot: ${yamlString(config.creatorRoot)}`,
    `    atlasRoot: ${yamlString(config.atlasRoot)}`,
    `    dataDir: ${yamlString(config.dataDir)}`,
    `    subtitleSkillDir: ${yamlString(config.subtitleSkillDir)}`,
    `    coverSkillDir: ${yamlString(config.coverSkillDir)}`,
    `    videoPublisherSkillDir: ${yamlString(config.videoPublisherSkillDir)}`,
    `    trellisProjectsRoot: ${yamlString(config.trellisProjectsRoot)}`,
    `    obsidianExecutable: ${yamlString(config.obsidianExecutable)}`,
    "    enabledPublishTargets: []",
    "    externalActionsEnabled: false",
    "",
  ].join("\n");
  for (const target of [paths.profileManifest, paths.profilePatch, paths.profileWorkspace, paths.safetyManifest]) {
    await prepareLabPath(paths.root, target);
    await mkdir(dirname(target), { recursive: true });
  }
  await writeFile(paths.profileManifest, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
  await writeFile(paths.profilePatch, patch, "utf8");
  await writeFile(paths.profileWorkspace, "packages:\n  - .\n\nnodeLinker: hoisted\nautoInstallPeers: false\n", "utf8");
  await writeFile(paths.safetyManifest, `${JSON.stringify(config, null, 2)}\n`, "utf8");
  console.log(`Lab Web profile 已写入：${paths.profile}`);
  return { paths, config };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) await writeLabConfig(process.cwd());
