#!/usr/bin/env node
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { labPaths, prepareLabPath } from "./lab-paths.mjs";
import { setupLab } from "./lab-setup.mjs";

function yamlString(value) {
  return JSON.stringify(value);
}

export const LAB_WRITABLE_PATH_KEYS = Object.freeze([
  "libraryRoot",
  "creatorRoot",
  "atlasRoot",
  "trellisProjectsRoot",
  "dataDir",
  "subtitleSkillDir",
  "coverSkillDir",
  "videoPublisherSkillDir",
]);

export const LAB_PROFILE_WORKSPACE = "packages:\n  - .\n\nnodeLinker: hoisted\nautoInstallPeers: false\n";

export const DESKTOP_PROFILE_SELECTION_STATE = Object.freeze({
  version: 1,
  active: "web",
  lastKnownGood: "web",
});

export const DESKTOP_MARKET_SELECTION_STATE = Object.freeze({
  version: 1,
  requested: "disabled",
  legacyDefaulted: false,
});

export const DESKTOP_SETTINGS_DOCUMENT = "dsh-desktop:\n  mode: compatibility\n";

export function createLabSafetyConfig(paths) {
  return {
    externalActionsEnabled: false,
    libraryRoot: paths.library,
    creatorRoot: paths.library,
    atlasRoot: paths.atlas,
    trellisProjectsRoot: paths.trellis,
    dataDir: paths.data,
    subtitleSkillDir: join(paths.skills, "subtitle"),
    coverSkillDir: join(paths.skills, "cover"),
    videoPublisherSkillDir: join(paths.skills, "video-publisher"),
    obsidianExecutable: "",
    enabledPublishTargets: [],
    credentials: {},
    lab: { isolated: true, repositoryRoot: paths.root },
  };
}

export function createLabProfileManifest(paths) {
  return {
    name: "dsh-profile-web-muzi-creator-lab",
    private: true,
    dependencies: { "dsh-muzi-creator": `link:${paths.root.replaceAll("\\", "/")}` },
    dsh: {
      profile: {
        bundles: ["@deepseek-ai/dsh-base", "@deepseek-ai/dsh-web-app", "dsh-muzi-creator"],
      },
    },
  };
}

export function createLabProfilePatch(config) {
  return [
    "# Generated by pnpm lab:config. All writable Muzi Creator paths remain under .lab.",
    "- id: dsh-muzi-creator",
    "  config:",
    `    libraryRoot: ${yamlString(config.libraryRoot)}`,
    `    creatorRoot: ${yamlString(config.creatorRoot)}`,
    `    atlasRoot: ${yamlString(config.atlasRoot)}`,
    `    dataDir: ${yamlString(config.dataDir)}`,
    `    subtitleSkillDir: ${yamlString(config.subtitleSkillDir)}`,
    `    coverSkillDir: ${yamlString(config.coverSkillDir)}`,
    `    videoPublisherSkillDir: ${yamlString(config.videoPublisherSkillDir)}`,
    `    trellisProjectsRoot: ${yamlString(config.trellisProjectsRoot)}`,
    `    obsidianExecutable: ${yamlString(config.obsidianExecutable)}`,
    "    enabledPublishTargets: []",
    "    externalActionsEnabled: false",
    "",
  ].join("\n");
}

/** Returns the Desktop-owned selected-profile state used by Desktop 2.0.2. */
export function createDesktopProfileSelectionState() {
  return { ...DESKTOP_PROFILE_SELECTION_STATE };
}

/** Returns Desktop 2.0.2's explicit disabled-Market selection. */
export function createDesktopMarketSelectionState() {
  return { ...DESKTOP_MARKET_SELECTION_STATE };
}

export async function writeLabConfig(repositoryRoot) {
  const paths = await setupLab(repositoryRoot);
  const config = createLabSafetyConfig(paths);
  for (const directory of [config.subtitleSkillDir, config.coverSkillDir, config.videoPublisherSkillDir]) {
    await prepareLabPath(paths.root, directory);
    await mkdir(directory, { recursive: true });
  }
  const manifest = createLabProfileManifest(paths);
  const patch = createLabProfilePatch(config);
  for (const target of [
    paths.profileManifest,
    paths.profilePatch,
    paths.profileWorkspace,
    paths.desktopProfileManifest,
    paths.desktopProfilePatch,
    paths.desktopProfileWorkspace,
    paths.desktopProfileSelection,
    paths.desktopMarketSelection,
    paths.desktopSettings,
    paths.safetyManifest,
  ]) {
    await prepareLabPath(paths.lab, target);
    await mkdir(dirname(target), { recursive: true });
  }
  await writeFile(paths.profileManifest, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
  await writeFile(paths.profilePatch, patch, "utf8");
  await writeFile(paths.profileWorkspace, LAB_PROFILE_WORKSPACE, "utf8");
  await writeFile(paths.desktopProfileManifest, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
  await writeFile(paths.desktopProfilePatch, patch, "utf8");
  await writeFile(paths.desktopProfileWorkspace, LAB_PROFILE_WORKSPACE, "utf8");
  await writeFile(paths.desktopProfileSelection, `${JSON.stringify(createDesktopProfileSelectionState(), null, 2)}\n`, "utf8");
  await writeFile(paths.desktopMarketSelection, `${JSON.stringify(createDesktopMarketSelectionState(), null, 2)}\n`, "utf8");
  await writeFile(paths.desktopSettings, DESKTOP_SETTINGS_DOCUMENT, "utf8");
  await writeFile(paths.safetyManifest, `${JSON.stringify(config, null, 2)}\n`, "utf8");
  console.log(`Lab Web 与 Desktop profile 已写入：${paths.profile}`);
  return { paths, config };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) await writeLabConfig(process.cwd());
