import type { InvocationDescriptor } from "@deepseek-ai/dsh-typert-protocol";
import { z } from "zod";
import { githubRequestSchema, githubResultSchema } from "./trellisGithubSchemas.ts";
import { addVideoAccountSchema, setVideoAccountEnabledSchema, videoAccountLoginSchema, videoAccountManagementSchema, videoConnectionRequestSchema, videoConnectionReopenSchema } from "./videoAccountSchemas.ts";
import { publishFlowSchema, publishFlowGetSchema, publishFlowPrepareSchema, publishFlowActionSchema } from "./publishFlowSchemas.ts";


import {
  capabilitiesResultSchema,
  contentDetailSchema,
  coverThumbResultSchema,
  idRequestSchema,
  librarySettingsSchema,
  listContentsRequestSchema,
  listContentsResultSchema,
  setLibraryRootRequestSchema,
  setObsidianExecutableRequestSchema,
  setTrellisProjectsRootRequestSchema,
  createContentRequestSchema,
  createContentResultSchema,
  setContentStageRequestSchema,
  setProfileRequestSchema,
  setScriptRulesRequestSchema,
  bindProductionProjectRequestSchema,
  bindStudioRequestSchema,
  setPublishRequestSchema,
  setScriptRequestSchema,
  subtitlePreviewResultSchema,
  subtitleTextResultSchema,
  revisionResultSchema,
  syncPublishRequestSchema,
  syncPublishResultSchema,
  videoPlaybackResultSchema,
  articleMediaResultSchema,
  waitExportRequestSchema,
} from "./schemas.ts";
import {
  knowledgeGetRequestSchema,
  knowledgeHomeResultSchema,
  knowledgeListRequestSchema,
  knowledgeListResultSchema,
  knowledgePageSchema,
  knowledgePreviewResultSchema,
  knowledgeSearchRequestSchema,
  knowledgeSearchResultSchema,
  knowledgeStatusSchema,
  deleteMuziProjectResultSchema,
  muziArchiveRequestSchema,
  muziDocumentSaveRequestSchema,
  muziDocumentLocationRequestSchema,
  muziDocumentLocationSchema,
  muziDocumentOpenResultSchema,
  muziProjectCreateRequestSchema,
  muziProjectDetailSchema,
  muziProjectGetRequestSchema,
  muziProjectListRequestSchema,
  muziProjectListResultSchema,
  muziProjectStatusRequestSchema,
  muziPublicationSetRequestSchema,
  muziWorkspaceRevisionSchema,
  pendingKnowledgeFileSchema,
  pendingKnowledgeGetRequestSchema,
  pendingKnowledgeListRequestSchema,
  pendingKnowledgeListResultSchema,
  pendingKnowledgeReferenceSchema,
  videoAcceptanceBeginRequestSchema,
  videoAcceptanceFinalizeRequestSchema,
  videoAcceptanceFinalizeResultSchema,
  videoAcceptanceSessionResultSchema,
  videoMetricsSyncRequestSchema,
  videoMetricsSyncResultSchema,
  videoPublishCommitRequestSchema,
  videoPublishCapabilitiesResultSchema,
  videoPublishPrepareRequestSchema,
  videoPublishStatusRequestSchema,
  videoPublishStatusResultSchema,
  videoPublishTaskResultSchema,
} from "./muziSchemas.ts";
import {
  dailyHotResultSchema,
  getDailyHotRequestSchema,
} from "./dailyHotSchemas.ts";
import {
  archiveInspirationRequestSchema,
  deleteInspirationRequestSchema,
  deleteInspirationResultSchema,
  getInspirationRequestSchema,
  inspirationDetailSchema,
  inspirationItemSchema,
  inspirationOverviewSchema,
  inspirationReferenceSchema,
  inspirationRunSchema,
  inspirationTaskSchema,
  listInspirationsRequestSchema,
  markInspirationReadRequestSchema,
  openedInspirationReportSchema,
  openInspirationReportRequestSchema,
  runInspirationTaskNowRequestSchema,
  saveInspirationDraftRequestSchema,
  saveInspirationTaskRequestSchema,
  serializeInspirationReferenceRequestSchema,
  setInspirationTaskStateRequestSchema,
  startInspirationResearchRequestSchema,
  startInspirationResearchResultSchema,
  stopInspirationRunRequestSchema,
} from "./inspirationSchemas.ts";
import {
  archiveTrellisTaskRequestSchema,
  getTrellisProjectRequestSchema,
  prepareTrellisTaskArchiveRequestSchema,
  trellisArchivePreviewSchema,
  trellisArchiveResultSchema,
  trellisProjectDetailSchema,
  trellisProjectListResultSchema,
} from "./trellisSchemas.ts";

export const PACKAGE_NAME = "dsh-muzi-creator";
export const REMOTE_NAMESPACE = "mzCreator";

const emptyObjectSchema = z.object({});

function codec(typeSymbol: string, schema: z.ZodType<unknown>) {
  return { mode: "strict" as const, typeSymbol, schema };
}

function jsonParam(
  name: string,
  typeSymbol: string,
  schema: z.ZodType<unknown>,
): InvocationDescriptor["parameters"][number] {
  return {
    name,
    wire: name,
    source: "json",
    codec: codec(typeSymbol, schema),
  };
}

function invocation(
  method: string,
  request: z.ZodType<unknown>,
  result: z.ZodType<unknown>,
): InvocationDescriptor {
  return {
    id: `${PACKAGE_NAME}#${REMOTE_NAMESPACE}/${method}`,
    service: REMOTE_NAMESPACE,
    namespace: REMOTE_NAMESPACE,
    method,
    invocation: { kind: "direct" },
    parameters: [jsonParam("request", `${PACKAGE_NAME}#${method}Request`, request)],
    cancellation: { parameter: "signal" },
    result: codec(`${PACKAGE_NAME}#${method}Result`, result),
    sourceLocation: { file: "src/service.ts", line: 1, column: 1 },
  };
}

export const MZ_CREATOR_INVOCATIONS: readonly InvocationDescriptor[] = [
  invocation("listContents", listContentsRequestSchema, listContentsResultSchema),
  invocation("getContent", idRequestSchema, contentDetailSchema),
  invocation("getCoverThumb", idRequestSchema, coverThumbResultSchema),
  invocation("getVideoPlayback", idRequestSchema, videoPlaybackResultSchema),
  invocation("getArticleMedia", idRequestSchema, articleMediaResultSchema),
  invocation("getSubtitleText", idRequestSchema, subtitleTextResultSchema),
  invocation("getVideoAccounts", emptyObjectSchema, videoAccountManagementSchema),
  invocation("addVideoAccount", addVideoAccountSchema, videoAccountManagementSchema),
  invocation("setVideoAccountEnabled", setVideoAccountEnabledSchema, videoAccountManagementSchema),
  invocation("removeVideoAccount", videoAccountLoginSchema, videoAccountManagementSchema),
  invocation("openVideoAccountLogin", videoAccountLoginSchema, videoAccountManagementSchema),
  invocation("checkVideoAccountLogin", videoAccountLoginSchema, videoAccountManagementSchema),
  invocation("reconnectVideoAccount", videoAccountLoginSchema, videoAccountManagementSchema),
  invocation("pollVideoAccountConnection", videoConnectionRequestSchema, videoAccountManagementSchema),
  invocation("cancelVideoAccountConnection", videoConnectionRequestSchema, videoAccountManagementSchema),
  invocation("reopenVideoAccountConnection", videoConnectionReopenSchema, videoAccountManagementSchema),
  invocation("getPublishFlow", publishFlowGetSchema, publishFlowSchema.nullable()),
  invocation("preparePublishFlow", publishFlowPrepareSchema, publishFlowSchema),
  invocation("resumePublishFlow", publishFlowActionSchema, publishFlowSchema),
  invocation("invalidatePublishFlow", publishFlowActionSchema, publishFlowSchema),
  invocation("commitPublishFlow", publishFlowActionSchema, publishFlowSchema),
  invocation("getSettings", emptyObjectSchema, librarySettingsSchema),
  invocation("getCapabilities", emptyObjectSchema, capabilitiesResultSchema),
  invocation("getRevision", emptyObjectSchema, revisionResultSchema),
  invocation("setLibraryRoot", setLibraryRootRequestSchema, librarySettingsSchema),
  invocation("setTrellisProjectsRoot", setTrellisProjectsRootRequestSchema, librarySettingsSchema),
  invocation("setObsidianExecutable", setObsidianExecutableRequestSchema, librarySettingsSchema),
  invocation("refreshCatalog", emptyObjectSchema, listContentsResultSchema),
  invocation("createContent", createContentRequestSchema, createContentResultSchema),
  invocation("setContentStage", setContentStageRequestSchema, contentDetailSchema),
  invocation("setProfile", setProfileRequestSchema, librarySettingsSchema),
  invocation("setScriptRules", setScriptRulesRequestSchema, librarySettingsSchema),
  invocation("bindProductionProject", bindProductionProjectRequestSchema, contentDetailSchema),
  invocation("openProductionProjectFolder", idRequestSchema, contentDetailSchema),
  invocation("waitForExport", waitExportRequestSchema, contentDetailSchema),
  invocation("cancelWaitForExport", idRequestSchema, contentDetailSchema),
  invocation("bindStudio", bindStudioRequestSchema, contentDetailSchema),
  invocation("openStudio", idRequestSchema, contentDetailSchema),
  invocation("setPublish", setPublishRequestSchema, contentDetailSchema),
  invocation("syncPublish", syncPublishRequestSchema, syncPublishResultSchema),
  invocation("setScript", setScriptRequestSchema, contentDetailSchema),
  invocation("openSubtitlePreview", idRequestSchema, subtitlePreviewResultSchema),
  invocation("startSubtitleBurn", idRequestSchema, contentDetailSchema),
  invocation("startSubtitleGenerate", idRequestSchema, contentDetailSchema),
  invocation("startCoverGenerate", idRequestSchema, contentDetailSchema),
  invocation("listMuziProjects", muziProjectListRequestSchema, muziProjectListResultSchema),
  invocation("getMuziProject", muziProjectGetRequestSchema, muziProjectDetailSchema),
  invocation("getMuziProjectCover", muziProjectGetRequestSchema, coverThumbResultSchema),
  invocation("createMuziProject", muziProjectCreateRequestSchema, muziProjectDetailSchema),
  invocation("saveMuziDocument", muziDocumentSaveRequestSchema, muziProjectDetailSchema),
  invocation("setMuziProjectStatus", muziProjectStatusRequestSchema, muziProjectDetailSchema),
  invocation("setMuziPublication", muziPublicationSetRequestSchema, muziProjectDetailSchema),
  invocation("beginMuziVideoAcceptance", videoAcceptanceBeginRequestSchema.refine(request => request.capability === "metrics", "Publishing uses the content flow"), videoAcceptanceSessionResultSchema),
  invocation("getMuziVideoPublishCapabilities", emptyObjectSchema, videoPublishCapabilitiesResultSchema),
  invocation("finalizeMuziVideoAcceptance", videoAcceptanceFinalizeRequestSchema.refine(request => request.capability === "metrics", "Publishing uses the content flow"), videoAcceptanceFinalizeResultSchema),
  invocation("getMuziVideoPublishStatus", videoPublishStatusRequestSchema, videoPublishStatusResultSchema),
  invocation("syncMuziVideoMetrics", videoMetricsSyncRequestSchema, videoMetricsSyncResultSchema),
  invocation("archiveMuziProject", muziArchiveRequestSchema, muziProjectDetailSchema),
  invocation("deleteMuziProject", muziArchiveRequestSchema, deleteMuziProjectResultSchema),
  invocation("getMuziWorkspaceRevision", emptyObjectSchema, muziWorkspaceRevisionSchema),
  invocation("getMuziDocumentLocation", muziDocumentLocationRequestSchema, muziDocumentLocationSchema),
  invocation("openMuziDocumentInObsidian", muziDocumentLocationRequestSchema, muziDocumentOpenResultSchema),
  invocation("getKnowledgeStatus", emptyObjectSchema, knowledgeStatusSchema),
  invocation("getKnowledgeHome", emptyObjectSchema, knowledgeHomeResultSchema),
  invocation("getKnowledgePreview", emptyObjectSchema, knowledgePreviewResultSchema),
  invocation("listKnowledgeDirectory", knowledgeListRequestSchema, knowledgeListResultSchema),
  invocation("searchKnowledge", knowledgeSearchRequestSchema, knowledgeSearchResultSchema),
  invocation("getKnowledgePage", knowledgeGetRequestSchema, knowledgePageSchema),
  invocation("listPendingKnowledge", pendingKnowledgeListRequestSchema, pendingKnowledgeListResultSchema),
  invocation("getPendingKnowledgeFile", pendingKnowledgeGetRequestSchema, pendingKnowledgeFileSchema),
  invocation("serializePendingKnowledgeReference", pendingKnowledgeGetRequestSchema, pendingKnowledgeReferenceSchema),
  invocation("getDailyHot", getDailyHotRequestSchema, dailyHotResultSchema),
  invocation("listInspirations", listInspirationsRequestSchema, inspirationOverviewSchema),
  invocation("getInspirationRevision", emptyObjectSchema, revisionResultSchema),
  invocation("getInspiration", getInspirationRequestSchema, inspirationDetailSchema),
  invocation("saveInspirationDraft", saveInspirationDraftRequestSchema, inspirationItemSchema),
  invocation("startInspirationResearch", startInspirationResearchRequestSchema, startInspirationResearchResultSchema),
  invocation("stopInspirationRun", stopInspirationRunRequestSchema, inspirationRunSchema),
  invocation("saveInspirationTask", saveInspirationTaskRequestSchema, inspirationTaskSchema),
  invocation("setInspirationTaskState", setInspirationTaskStateRequestSchema, inspirationTaskSchema),
  invocation("runInspirationTaskNow", runInspirationTaskNowRequestSchema, inspirationRunSchema),
  invocation("markInspirationRead", markInspirationReadRequestSchema, inspirationRunSchema),
  invocation("archiveInspiration", archiveInspirationRequestSchema, inspirationItemSchema),
  invocation("deleteInspiration", deleteInspirationRequestSchema, deleteInspirationResultSchema),
  invocation("openInspirationReportInObsidian", openInspirationReportRequestSchema, openedInspirationReportSchema),
  invocation("serializeInspirationReference", serializeInspirationReferenceRequestSchema, inspirationReferenceSchema),
  invocation("manageTrellisGithub", githubRequestSchema, githubResultSchema),
  invocation("listTrellisProjects", emptyObjectSchema, trellisProjectListResultSchema),
  invocation("getTrellisProject", getTrellisProjectRequestSchema, trellisProjectDetailSchema),
  invocation("prepareTrellisTaskArchive", prepareTrellisTaskArchiveRequestSchema, trellisArchivePreviewSchema),
  invocation("archiveTrellisTask", archiveTrellisTaskRequestSchema, trellisArchiveResultSchema),
];
