import { z } from "zod";
import { muziVideoPlatformSchema, videoPublishCapabilitiesResultSchema } from "./muziSchemas.ts";

/** Account identifiers are generated by the publisher and remain stable across logins. */
export const videoAccountKeySchema = z.object({
  platform: muziVideoPlatformSchema,
  accountProfile: z.string().regex(/^[a-zA-Z0-9][a-zA-Z0-9._-]{0,79}$/),
});
export const addVideoAccountSchema = z.object({
  platform: muziVideoPlatformSchema,
  confirmed: z.literal(true),
}).strict();
export const videoConnectionRequestSchema = z.object({ connectionId: z.string().regex(/^vac-[a-f0-9]{24}$/) }).strict();
export const videoConnectionReopenSchema = videoConnectionRequestSchema.extend({ confirmed: z.literal(true) });
export const setVideoAccountEnabledSchema = videoAccountKeySchema.extend({ enabled: z.boolean() }).strict();
export const videoAccountLoginSchema = videoAccountKeySchema.extend({ confirmed: z.literal(true) }).strict();
export const registeredVideoAccountSchema = videoAccountKeySchema.extend({ displayName: z.string().min(1), enabled: z.boolean(), platformAccountId: z.string().min(1).nullable().default(null), connectedAt: z.string().datetime().nullable().default(null), removalPending: z.boolean().optional() });
export const videoConnectionSchema = z.object({
  connectionId: z.string().regex(/^vac-[a-f0-9]{24}$/), platform: muziVideoPlatformSchema, accountProfile: videoAccountKeySchema.shape.accountProfile,
  state: z.enum(["waiting_login", "checking", "connected", "needs_attention", "failed", "cancelled", "expired"]),
  createdAt: z.string().datetime(), expiresAt: z.string().datetime(), displayName: z.string().nullable(), message: z.string().nullable(), account: registeredVideoAccountSchema.nullable(),
});
export const videoAccountLoginStatusSchema = videoAccountKeySchema.extend({
  state: z.enum(["unverified", "unknown", "verified", "login_required", "identity_mismatch", "challenge"]),
  checkedAt: z.string().datetime().nullable(),
});
export const videoAccountRegistrySchema = z.object({
  accounts: z.array(registeredVideoAccountSchema),
  loginStatuses: z.array(videoAccountLoginStatusSchema),
  connections: z.array(videoConnectionSchema).default([]),
  connection: videoConnectionSchema.optional(),
});
export const videoAccountManagementSchema = videoAccountRegistrySchema.extend({
  capabilities: videoPublishCapabilitiesResultSchema,
  browserActionsEnabled: z.boolean(),
  connectionPollIntervalMs: z.number().int().min(1000).default(2000),
});
export type VideoAccount = z.infer<typeof registeredVideoAccountSchema>;
export type AddVideoAccount = z.infer<typeof addVideoAccountSchema>;
export type SetVideoAccountEnabled = z.infer<typeof setVideoAccountEnabledSchema>;
export type VideoAccountLogin = z.infer<typeof videoAccountLoginSchema>;
export type VideoAccountManagement = z.infer<typeof videoAccountManagementSchema>;
export type VideoConnection = z.infer<typeof videoConnectionSchema>;
export type VideoConnectionRequest = z.infer<typeof videoConnectionRequestSchema>;
export type VideoConnectionReopen = z.infer<typeof videoConnectionReopenSchema>;

/** The content overview and publishing panel share one account registry. */
export interface VideoAccountFace {
  list: () => Promise<VideoAccountManagement>;
  add: (request: AddVideoAccount) => Promise<VideoAccountManagement>;
  setEnabled: (request: SetVideoAccountEnabled) => Promise<VideoAccountManagement>;
  /** Remove the binding and its isolated browser login after explicit confirmation. */
  remove: (request: VideoAccountLogin) => Promise<VideoAccountManagement>;
  openLogin: (request: VideoAccountLogin) => Promise<VideoAccountManagement>;
  checkLogin: (request: VideoAccountLogin) => Promise<VideoAccountManagement>;
  reconnect: (request: VideoAccountLogin) => Promise<VideoAccountManagement>;
  pollConnection: (request: VideoConnectionRequest) => Promise<VideoAccountManagement>;
  cancelConnection: (request: VideoConnectionRequest) => Promise<VideoAccountManagement>;
  reopenConnection: (request: VideoConnectionReopen) => Promise<VideoAccountManagement>;
}
