export const githubSourceZh = {
  "githubSource.creator": "创作内容来源",
  "githubSource.knowledge": "知识来源",
  "githubSource.settingsHint": "GitHub 来源操作即时生效，不受「放弃」影响。远程仓库只读，内容只显示已推送的提交。",
  "githubSource.localSettingsHint": "本地目录需点击下方「保存」后生效；切换来源即时生效。",
  "githubSource.remoteHint": "输入 GitHub 仓库地址、用户主页或用户名，再选择分支。插件只读取快照，不执行仓库脚本，也不会把修改写回 GitHub。",
  "githubSource.local": "本地目录",
  "githubSource.remote": "GitHub 仓库",
  "githubSource.query": "GitHub 仓库地址、用户主页或用户名",
  "githubSource.search": "读取仓库",
  "githubSource.repository": "选择仓库",
  "githubSource.branch": "选择分支",
  "githubSource.connect": "连接来源",
  "githubSource.refresh": "刷新快照",
  "githubSource.remove": "移除远程来源",
  "githubSource.empty": "没有可访问的仓库，请检查地址或授权范围。",
  "githubSource.noBranches": "此仓库还没有可读取的分支。",
  "githubSource.snapshot": "当前快照",
  "githubSource.snapshotEmpty": "尚未同步 GitHub 快照。",
  "githubSource.stale": "网络读取失败，当前显示上次成功快照。",
  "githubSource.readOnly": "远程来源只读；请在 GitHub 仓库中修改并推送，然后刷新。",
  "githubSource.bind": "连接 GitHub 账号",
  "githubSource.bound": "已保存 GitHub 授权，读取私有仓库时会核验权限。",
  "githubSource.unbind": "断开账号",
  "githubSource.setup": "公开仓库无需授权；读取私有仓库需要管理员配置 GitHub App Client ID 并开启 Device flow。",
  "githubSource.device": "前往 GitHub 输入验证码",
  "githubSource.check": "我已授权，检查连接",
  "githubSource.pending": "等待 GitHub 授权，验证码有效期至",
  "githubSource.syncing": "正在同步 GitHub 快照，首次同步可能需要一些时间…",
  "githubSource.failed": "操作失败，请重试。",
} as const;

export const githubSourceEn: Record<keyof typeof githubSourceZh, string> = {
  "githubSource.creator": "Creator content source",
  "githubSource.knowledge": "Knowledge source",
  "githubSource.settingsHint": "GitHub source actions apply immediately and are not reverted by Discard. Remote repositories are read-only and only pushed commits are shown.",
  "githubSource.localSettingsHint": "Click Save below to apply the local folder. Source switching applies immediately.",
  "githubSource.remoteHint": "Enter a GitHub repository address, profile URL, or username, then choose a branch. The plugin reads snapshots only; it never runs repository scripts or writes back to GitHub.",
  "githubSource.local": "Local folder",
  "githubSource.remote": "GitHub repository",
  "githubSource.query": "GitHub repository address, profile URL, or username",
  "githubSource.search": "Load repository",
  "githubSource.repository": "Choose repository",
  "githubSource.branch": "Choose branch",
  "githubSource.connect": "Connect source",
  "githubSource.refresh": "Refresh snapshot",
  "githubSource.remove": "Remove remote source",
  "githubSource.empty": "No accessible repository. Check the address or granted access.",
  "githubSource.noBranches": "This repository has no readable branches yet.",
  "githubSource.snapshot": "Current snapshot",
  "githubSource.snapshotEmpty": "No GitHub snapshot has been synced yet.",
  "githubSource.stale": "The network read failed; showing the last successful snapshot.",
  "githubSource.readOnly": "Remote sources are read-only. Update and push the GitHub repository, then refresh.",
  "githubSource.bind": "Connect GitHub account",
  "githubSource.bound": "GitHub authorization saved. Private repository access will be checked when read.",
  "githubSource.unbind": "Disconnect account",
  "githubSource.setup": "Public repositories need no authorization. Private repositories require an administrator-configured GitHub App Client ID with Device flow enabled.",
  "githubSource.device": "Enter the code on GitHub",
  "githubSource.check": "Check authorization",
  "githubSource.pending": "Waiting for GitHub authorization. Code expires at",
  "githubSource.syncing": "Syncing the GitHub snapshot. The first sync may take a little time…",
  "githubSource.failed": "The operation failed. Please retry.",
};
