export const overviewZh = {
  "overview.updated": "最近更新于",
  "overview.timeUnavailable": "时间不可用",
  "overview.documents": "稿件",
  "overview.stale": "来源已更新，待重新加工",
  "overview.production": "视频制作",
  "overview.productionLoading": "正在读取视频制作信息",
  "overview.productionError": "视频制作信息不可用",
  "overview.nextAction": "下一步：",
  "overview.openProduction": "查看制作",
  "overview.publication": "发布",
  "overview.publicationHint": "发布记录与任务状态分开显示。",
  "overview.managePublication": "管理发布",
  "overview.unpublished": "未记录发布",
  "overview.platformDraft": "平台草稿",
  "overview.scheduled": "已排程",
  "overview.published": "已发布",
  "overview.openWork": "打开作品",
  "overview.openArticle": "打开文章",
  "overview.task.readyDraft": "平台草稿已备",
  "overview.task.readyPublish": "待确认立即发布",
  "overview.task.readySchedule": "待确认定时提交",
  "overview.task.published": "发布任务已确认",
  "overview.task.scheduled": "定时发布已确认",
  "overview.task.blocked": "发布任务已阻塞",
  "overview.task.unknown": "提交结果未知，需核查",
  "overview.task.preparing": "正在准备发布任务",
  "overview.task.new": "尚未准备发布任务",
  "overview.task.other": "发布任务：",
  "overview.blog": "博客文章",
  "overview.stage.idea": "灵感",
  "overview.stage.research": "研究中",
  "overview.stage.mother_draft": "母内容草稿",
  "overview.stage.adaptation": "渠道改编",
  "overview.stage.review": "审阅中",
  "overview.stage.ready": "已就绪",
  "overview.stage.archived": "已归档",
  "overview.productionStage.preparing": "制作准备",
  "overview.productionStage.recording": "录制",
  "overview.productionStage.editing": "剪辑与导出",
  "overview.productionStage.finishing": "字幕与封面",
  "overview.productionStage.ready": "成片就绪",
  "overview.next.preparing": "确认视频稿，准备进入录制",
  "overview.next.recording": "完成录制并进入剪辑",
  "overview.next.exportError": "检查导出任务并重新导出视频",
  "overview.next.waitingExport": "等待导出视频稳定落盘",
  "overview.next.editing": "完成剪辑并导出视频",
  "overview.next.complete": "—",
  "overview.next.waitingFinish": "等待字幕与封面处理完成",
  "overview.next.finishError": "检查并重试失败的制作任务",
  "overview.next.finishBoth": "生成并确认字幕与封面",
  "overview.next.subtitle": "生成并确认字幕",
  "overview.next.cover": "生成并确认封面",
  "overview.document.mother": "母内容",
  "overview.document.video": "视频稿",
  "overview.document.wechat": "公众号",
  "overview.document.xiaohongshu": "小红书",
  "overview.document.blog": "博客",
  "overview.document.not_started": "未开始",
  "overview.document.draft": "草稿",
  "overview.document.review": "审阅中",
  "overview.document.ready": "已就绪",
} as const;

export type OverviewCopyKey = keyof typeof overviewZh;

export const overviewEn: Record<OverviewCopyKey, string> = {
  "overview.updated": "Updated",
  "overview.timeUnavailable": "Time unavailable",
  "overview.documents": "Documents",
  "overview.stale": "Source changed; revise this document",
  "overview.production": "Video production",
  "overview.productionLoading": "Loading video production details",
  "overview.productionError": "Video production details are unavailable",
  "overview.nextAction": "Next:",
  "overview.openProduction": "View production",
  "overview.publication": "Publication",
  "overview.publicationHint": "Recorded publication facts and task status are shown separately.",
  "overview.managePublication": "Manage publication",
  "overview.unpublished": "No publication recorded",
  "overview.platformDraft": "Platform draft",
  "overview.scheduled": "Scheduled",
  "overview.published": "Published",
  "overview.openWork": "Open work",
  "overview.openArticle": "Open article",
  "overview.task.readyDraft": "Platform draft prepared",
  "overview.task.readyPublish": "Confirmation needed to publish",
  "overview.task.readySchedule": "Confirmation needed to schedule",
  "overview.task.published": "Publication task confirmed",
  "overview.task.scheduled": "Scheduled publication confirmed",
  "overview.task.blocked": "Publication task is blocked",
  "overview.task.unknown": "Submission result is unknown; check it",
  "overview.task.preparing": "Preparing publication task",
  "overview.task.new": "Publication task has not been prepared",
  "overview.task.other": "Publication task:",
  "overview.blog": "Blog article",
  "overview.stage.idea": "Idea",
  "overview.stage.research": "Research",
  "overview.stage.mother_draft": "Mother draft",
  "overview.stage.adaptation": "Adaptation",
  "overview.stage.review": "In review",
  "overview.stage.ready": "Ready",
  "overview.stage.archived": "Archived",
  "overview.productionStage.preparing": "Preparation",
  "overview.productionStage.recording": "Recording",
  "overview.productionStage.editing": "Editing and export",
  "overview.productionStage.finishing": "Subtitles and cover",
  "overview.productionStage.ready": "Video ready",
  "overview.next.preparing": "Confirm the video script and prepare to record",
  "overview.next.recording": "Finish recording and begin editing",
  "overview.next.exportError": "Check the export task and export the video again",
  "overview.next.waitingExport": "Wait for the exported video to settle",
  "overview.next.editing": "Finish editing and export the video",
  "overview.next.complete": "—",
  "overview.next.waitingFinish": "Wait for subtitle and cover processing",
  "overview.next.finishError": "Check failed production work before retrying it",
  "overview.next.finishBoth": "Create and confirm subtitles and a cover",
  "overview.next.subtitle": "Create and confirm subtitles",
  "overview.next.cover": "Create and confirm a cover",
  "overview.document.mother": "Mother content",
  "overview.document.video": "Video script",
  "overview.document.wechat": "WeChat article",
  "overview.document.xiaohongshu": "Xiaohongshu",
  "overview.document.blog": "Blog",
  "overview.document.not_started": "Not started",
  "overview.document.draft": "Draft",
  "overview.document.review": "In review",
  "overview.document.ready": "Ready",
};
