export const githubZh = {
  "github.sources": "项目来源",
  "github.settingsHint": "GitHub 配置操作即时生效，不受「放弃」影响。",
  "github.localSettingsHint": "本地项目目录需点击下方「保存」后生效；切换来源即时生效。",
  "github.syncing": "正在读取 Trellis 任务，首次同步可能需要一些时间…",
  "github.local": "本地目录",
  "github.remote": "GitHub 仓库",
  "github.query": "仓库链接或 GitHub 用户名",
  "github.search": "读取仓库",
  "github.repository": "选择仓库",
  "github.branch": "选择分支",
  "github.add": "添加项目",
  "github.empty": "没有可访问的仓库，请检查链接或授权范围。",
  "github.hint": "读取所选分支的 .trellis/tasks，仅展示已推送的任务与验证材料。",
  "github.bind": "连接 GitHub",
  "github.bound": "已保存 GitHub 授权，读取仓库时核验权限。",
  "github.unbind": "断开账号",
  "github.setup": "账号授权尚未配置。可以直接添加公开仓库；管理员配置 GitHub App Client ID 并开启 Device flow 后，即可连接账号。",
  "github.device": "前往 GitHub 输入验证码",
  "github.check": "我已授权，检查连接",
  "github.pending": "等待 GitHub 授权，验证码有效期至",
  "github.failed": "操作失败，请重试",
  "github.remove": "移除项目连接",
  "github.open": "查看 GitHub 仓库",
  "github.stale": "同步失败，当前为上次结果",
  "github.readonly": "远程任务只读；请在项目中更新或归档，推送后刷新。",
  "github.noBranches": "此仓库还没有可读取的分支。",
  "github.noProjects": "尚未添加 GitHub 项目，请在设置 → 插件 → 个人内容工作台 → 项目来源中添加仓库。",
} as const;

export const githubEn: Record<keyof typeof githubZh, string> = {
  "github.sources": "Project sources",
  "github.settingsHint": "GitHub configuration actions apply immediately and are not reverted by Discard.",
  "github.localSettingsHint": "Click Save below to apply the local project folder. Source switching applies immediately.",
  "github.syncing": "Reading Trellis tasks. The first sync may take a little time…",
  "github.local": "Local folder",
  "github.remote": "GitHub repositories",
  "github.query": "Repository URL or GitHub username",
  "github.search": "Load repositories",
  "github.repository": "Choose a repository",
  "github.branch": "Choose a branch",
  "github.add": "Add project",
  "github.empty": "No accessible repositories. Check the URL or granted access.",
  "github.hint": "Read .trellis/tasks on the selected branch. Only pushed tasks and evidence are included.",
  "github.bind": "Connect GitHub",
  "github.bound": "GitHub authorization saved. Access is checked when reading repositories.",
  "github.unbind": "Disconnect account",
  "github.setup": "Account authorization is not configured. Public repositories work without it. An administrator must configure a GitHub App Client ID and enable Device flow to connect an account.",
  "github.device": "Enter the code on GitHub",
  "github.check": "Check authorization",
  "github.pending": "Waiting for GitHub authorization. Code expires at",
  "github.failed": "The operation failed. Please retry.",
  "github.remove": "Remove project connection",
  "github.open": "View repository on GitHub",
  "github.stale": "Sync failed; showing the previous snapshot",
  "github.readonly": "Remote tasks are read-only. Update or archive them in the project, push, then refresh.",
  "github.noBranches": "This repository has no readable branches yet.",
  "github.noProjects": "No GitHub projects yet. Add a repository in Settings → Plugins → Personal content workbench → Project sources.",
};
